spring:
  application:
    name: projeto-eco
  datasource:
    url: jdbc:postgresql://localhost:5432/eco
    username: root
    password: 7422
    driver-class-name: org.postgresql.Driver
file:
  upload-dir: uploads/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs