spring:
  application:
    name: projeto-eco
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mysql://localhost:3306/eco?useTimezone=true&serverTimezone=UTC
    username: root
    password: 7422
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
